In [5]:
import numpy as np

dizi=np.full((4,3),5)
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
dizi=np.array(["elma","erik","iğde"])

dizi

array(['elma', 'erik', 'iğde'], dtype='<U4')

In [8]:
dizi=np.array([1,2,3])
dizi=np.array([1,2,3,14])

dizi.dtype


dtype('int32')

In [10]:
dizi=np.array([1,2,3,14], dtype=int)

In [11]:
birboyut=np.array([1,2,3,4])
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
birboyut

array([1, 2, 3, 4])

In [12]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.full((4,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [17]:
np.arange(2,22,5)

array([ 2,  7, 12, 17])

In [18]:
np.linspace(2,10,num=7)

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [19]:
np.random.randint(0,10,(5,2))

array([[9, 8],
       [6, 0],
       [1, 2],
       [5, 2],
       [7, 9]])

In [21]:
np.random.randint(0,10,5)

array([8, 9, 6, 0, 1])

In [24]:
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

(3, 4)

In [25]:
dizi.ndim

2

In [35]:
dizi.size

35