**numpy dizi işlemleri**

In [11]:
import numpy as np #numpy kutuphanesini np takma adi ile projeye dahil ediyoruz

In [43]:
dizi=np.full((4,3),5)#4satır 3sutunluk 5ten olusan dizi
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [3]:
#yeni bir numpy dizisi olusturuyoruz
np.array([1,2,3])

array([1, 2, 3])

In [4]:
#olusturdugumuz diziyi bir degiskene aktarvryoruz
dizi=np.array(["elma", "erik", "igde"])

In [5]:
dizi

array(['elma', 'erik', 'igde'], dtype='<U4')

In [6]:
dizi=np.array([1,2,3])

In [7]:
dizi=np.array([1,2,3.14])

In [8]:
dizi.dtype #dizinin degisken turunu verir. numpy dizilerinde elemanLlarin hepst aynri turdendir

dtype('float64')

In [9]:
dizi=np.array([1,2,3.14], dtype=int)

**numpy ile farkli boyutlarda dizi olusturma**

In [13]:
#bir boyutlu dizi olusturma
birboyut=np.array([1,2,3,4])
#ikt boyutlu dizi olusturma
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [14]:
birboyut

array([1, 2, 3, 4])

In [15]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**numpy yer tutucular**

In [16]:
np.zeros(7) #7 s1iftrdan olusan tek boyutLlu dizi olusturur

array([0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((2,3),dtype=int)#* sıfırdan olusan 2 boyutlu int dizi olusturur

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.full((4,3),5)#5 sayisindan olusan 2*3 Luk dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [20]:
np.arange(2,22,5)#baslangic,bitis ve artis degerine gore dizi olusturma

array([ 2,  7, 12, 17])

In [21]:
np.linspace(2,10,num=7) #baslangic¢c ve bitis degeri araliginda belirtilen miktarda esit aralik

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [22]:
np.random.randint(0,10,5)#@-1@ aral1ginda rastgele 5 sayidan olusan bir boyutlu dizi

array([8, 4, 2, 2, 0])

**diziler ile ilgili islemler**

In [23]:
#dizilerin eleman sayisinr Ogrenmek t¢in shape komutu kuLllanilir
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

(3, 4)

In [24]:
#ndim dizi boyutunu ogrenmek i¢in kullanilir
dizi.ndim

2

In [25]:
#s1ze dizidekt toplLam eleman sayirsini gosterir
dizi.size

12

In [26]:
dizi.itemsize #dizidekit her bir elemanin bayt cinsinden degerini verir

4

**5satır 7sütun olacak şekilde rastgele sayılardan oluşan int türünde bir dizi oluşturma.**

In [42]:
dizi = np.random.randint(0,20, size=(5, 7),dtype=int)
dizi

array([[16,  7, 14,  3, 14,  5, 10],
       [13, 15, 11, 16,  9, 18, 10],
       [16, 13, 10,  8,  1,  4,  9],
       [ 4,  5, 17,  5,  0,  9,  8],
       [10,  4,  1,  6,  8, 14,  1]])